version: '3.4'

services:
  currency-converter:
    image: currency-converter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
